name: fleximart
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.2+2

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  firebase_messaging: ^16.0.4
  cloud_functions: ^6.0.3
  http: ^1.2.2
  lottie: ^3.3.2
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  url_launcher: ^6.3.1
  image_picker_for_web: ^3.1.1
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/welcome screen logo.png.png
    - assets/logo/
